modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/LazrProductions/tanfluids/issues"

[[mods]]
modId="tanfluids"
version="1.0.0"
displayName="TAN Fluids"
updateJSONURL=""
displayURL=""
logoFile="tanfluids.png"
authors="LazrProductions"
credits=""
description="A simple mod that adds fluids for the Tough as Nails liquids."

[[dependencies.tanfluids]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tanfluids]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tanfluids]]
    modId="toughasnails"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"